### ISSUE TITLE
ConsoleProgressBar bugged when using CP77Tools with custom console settings

### ISSUE THREAD

**Issue by gibbed** [rfuzzo/CP77Tools#21]
I have custom console properties set up to make the buffer much longer, this is seemingly breaking CP77Tools via ConsoleProgressBar trying to do something stupid.

```
Cyberpunk 2077\archive\pc\content>dotnet "CP77Tools\bin\Release\net5.0\CP77Tools.dll" archive -e -p basegame_1_engine.archive -o basegame_1_engine
Loading Hashes...
Loaded Hashes.
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 9001.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at ConsoleProgressBar.SystemConsole.SetCursorPosition(Int32 left, Int32 top)
   at ConsoleProgressBar.ProgressBar.Dispose(Boolean disposing)
   at ConsoleProgressBar.ProgressBar.Dispose()
   at CP77Tools.Model.Archive.ExtractAll(DirectoryInfo outDir) in CP77Tools\Model\Archive.cs:line 278
   at CP77Tools.ConsoleFunctions.ArchiveTask(String path, String outpath, Boolean extract, Boolean dump, Boolean list, Boolean uncook, EUncookExtension uext, UInt64 hash) in CP77Tools\ArchiveTask.cs:line 87
```

![Untitled](https://user-images.githubusercontent.com/85170/102592147-ab8a1900-40d8-11eb-9f4e-516e9060773c.png)

**Comment by Offline-R503B** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/64mYhNeg/14-github)
